# WALA Configuration Settings

# Network Configuration
DEFAULT_SERVER_HOST = '10.10.5.218'
DEFAULT_SERVER_PORT = 8888
BUFFER_SIZE = 4096
MAX_CONNECTIONS = 50

RSA_KEY_SIZE = 2048
DES_KEY_SIZE = 8
DES_BLOCK_SIZE = 8

DATABASE_FILE = 'wala.db'

MSG_TYPE_LOGIN = 'LOGIN'
MSG_TYPE_REGISTER = 'REGISTER'
MSG_TYPE_PUBLIC_KEY = 'PUBLIC_KEY'
MSG_TYPE_SESSION_KEY = 'SESSION_KEY'
MSG_TYPE_CHAT_MESSAGE = 'CHAT_MESSAGE'
MSG_TYPE_KEY_REQUEST = 'KEY_REQUEST'
MSG_TYPE_KEY_RESPONSE = 'KEY_RESPONSE'
MSG_TYPE_KEY_ROTATION_REQUEST = 'KEY_ROTATION_REQUEST'
MSG_TYPE_ERROR = 'ERROR'
MSG_TYPE_SUCCESS = 'SUCCESS'
MSG_TYPE_USER_LIST = 'USER_LIST'
MSG_TYPE_LOGOUT = 'LOGOUT'

ERROR_INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
ERROR_USER_NOT_FOUND = 'USER_NOT_FOUND'
ERROR_USER_OFFLINE = 'USER_OFFLINE'
ERROR_INVALID_MESSAGE = 'INVALID_MESSAGE'
ERROR_CRYPTO_ERROR = 'CRYPTO_ERROR'

LOG_FORMAT = '[%(asctime)s] %(levelname)s: %(message)s'
LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'

# Security Settings
PASSWORD_MIN_LENGTH = 6
SESSION_TIMEOUT = 3600
KEY_ROTATION_INTERVAL = 86400  # 24 hours in seconds
KEY_ROTATION_CHECK_INTERVAL = 3600  # Check every hour